FROM nginx:alpine

COPY dist /usr/share/nginx/html
COPY nginx.conf.template /etc/nginx/templates/default.conf.template

ENV BACKEND_UPSTREAM=http://backend:8001
ENV NGINX_SERVER_NAME=_

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
