# -*- coding: utf-8 -*-

DOWNLOAD_STATUS_SUCCESS = "success"
DOWNLOAD_STATUS_FAILED = "failed"
DOWNLOAD_STATUS_SKIPPED = "skipped"
DOWNLOAD_STATUS_SUBMITTED = "submitted"
DOWNLOAD_STATUS_ALL = "all"

DOWNLOAD_HISTORY_STATUSES = {
    DOWNLOAD_STATUS_SUCCESS,
    DOWNLOAD_STATUS_FAILED,
    DOWNLOAD_STATUS_SKIPPED,
    DOWNLOAD_STATUS_SUBMITTED,
}
