# -*- coding: utf-8 -*-

PENDING_TRANSFER_STATUS_PENDING = "pending"
PENDING_TRANSFER_STATUS_APPROVED = "approved"
PENDING_TRANSFER_STATUS_REJECTED = "rejected"
PENDING_TRANSFER_STATUS_RESOLVED = "resolved"
PENDING_TRANSFER_STATUS_ALL = "all"

PENDING_TRANSFER_ACTIVE_STATUSES = {
    PENDING_TRANSFER_STATUS_PENDING,
}

PENDING_TRANSFER_TERMINAL_STATUSES = {
    PENDING_TRANSFER_STATUS_APPROVED,
    PENDING_TRANSFER_STATUS_REJECTED,
    PENDING_TRANSFER_STATUS_RESOLVED,
}

PENDING_TRANSFER_STATUSES = PENDING_TRANSFER_ACTIVE_STATUSES | PENDING_TRANSFER_TERMINAL_STATUSES
