# -*- coding: utf-8 -*-

TASK_STATUS_QUEUED = "queued"
TASK_STATUS_RUNNING = "running"
TASK_STATUS_CANCEL_REQUESTED = "cancel_requested"
TASK_STATUS_CANCELLED = "cancelled"
TASK_STATUS_COMPLETED = "completed"
TASK_STATUS_FAILED = "failed"
TASK_STATUS_PARTIAL_FAILED = "partial_failed"

TASK_STATUS_ALL = "all"
ACTIVE_TASK_STATUSES = {TASK_STATUS_QUEUED, TASK_STATUS_RUNNING, TASK_STATUS_CANCEL_REQUESTED}
CANCELLABLE_TASK_STATUSES = ACTIVE_TASK_STATUSES
FAILED_TASK_STATUSES = {TASK_STATUS_FAILED, TASK_STATUS_PARTIAL_FAILED}
FINISHED_TASK_STATUSES = {
    TASK_STATUS_COMPLETED,
    TASK_STATUS_FAILED,
    TASK_STATUS_CANCELLED,
    TASK_STATUS_PARTIAL_FAILED,
}
VISIBLE_TASK_STATUSES = {
    TASK_STATUS_ALL,
    TASK_STATUS_QUEUED,
    TASK_STATUS_RUNNING,
    TASK_STATUS_CANCEL_REQUESTED,
    TASK_STATUS_CANCELLED,
    TASK_STATUS_COMPLETED,
    TASK_STATUS_FAILED,
    TASK_STATUS_PARTIAL_FAILED,
}
